force-app/main/default/objects/Trigger_Bypass__c/Trigger_Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Provides the ability to disable trigger functionality on a trigger-by-trigger basis or simply all triggers.</description>
    <label>Trigger Bypass</label>
</CustomObject>

force-app/main/default/objects/Trigger_Bypass__c/fields/Bypass_All__c.field-meta.xml
<CustomField>
    <fullName>Bypass_All__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows for the ability to bypass all triggers that utilize the established trigger framework.</description>
    <inlineHelpText>Allows for the ability to bypass all triggers that utilize the established trigger framework.</inlineHelpText>
    <label>Bypass All</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Bypass__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Bypass the Case trigger logic.</description>
    <inlineHelpText>Bypass the Case trigger logic.</inlineHelpText>
    <label>Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TriggerService.cls
public with sharing class TriggerService {
   
    public static Boolean isTriggerBypassed(String objectType) {
        Trigger_Bypass__c bypassSetting = Trigger_Bypass__c.getInstance();

        if(bypassSetting.Bypass_All__c) {
            return true;
        }

        switch on objectType {
            when 'Case' {
                if (bypassSetting.Case__c) {
                    return true;
                }
            }
            // ...expand for other objects here
        }

        return false;
    }
}